# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df57e42b0b56a49dad42267fb6f723e6c718a884f063d835404b2b8938b4ed58513de726c49f15e234dd6763763ce7daf8b1048b6ac9ff2a12b0454eb0bfc2aa

test:
  secret_key_base: 6048ac8c1d7f49c8e7677af299e6d493d77272da990edcfa4f2bbcc2d7eefc78a859ef815395498f5a7785dd769104a3fca7d49b2c53414981490bc7bc9b933a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
