# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b254951bb8a532b3027365aaab06d42351d6d9e2f0ebfb296e3470ac3d77dab512d3b623fae75420d6213e78e43f5afd6e76ffcc213fd3bfbf9749a0fbda4bee

test:
  secret_key_base: ce400d049bb173c8262a57b279070d0624a8abd01bd27d911f8e47aa7a5e44b640454de13cca52d6777b4da416c6a3bf7f9ce7ce085c4b19637a57d46859a0d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
